name: Sync Docs to Firebase

on:
  push:
    paths:
      - 'docs/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # 這裡幫您升級到最新版 24

      - name: Install Dependencies
        run: |
          npm init -y
          npm install firebase-admin

      - name: Run Sync Script
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true # 允許相容性設定
        run: node sync-to-firestore.js
